apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: nodelvmvpvs.lvm.node.storage
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lvm.node.storage
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: nodelvmvpvs
    # singular name to be used as an alias on the CLI and for display
    singular: nodelvmvpv
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: NodeLvmPhysicalVolume
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - lvmpv
  additionalPrinterColumns:
    - name: NodeName
      type: string
      description: node name
      JSONPath: .spec.nodeName
    - name: PvName
      type: string
      description: physical volume name 
      JSONPath: .spec.pvName
    - name: VGName
      type: string
      description: volume group name 
      JSONPath: .spec.vgName 
    - name: Format
      type: string
      description: physical volume's volume group name
      JSONPath: .spec.format    
    - name: PVSize
      type: number
      description: physical volume size
      JSONPath: .spec.vgsize    
    - name: FreePE
      type: number
      description: free size of physical volume
      JSONPath: .spec.vgfree                          
    - name: Attrs
      type: string
      description: attributions
      JSONPath: .spec.attrs                 
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp