apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: nodelvmstorages.lvm.node.storage
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lvm.node.storage
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: nodelvmstorages
    # singular name to be used as an alias on the CLI and for display
    singular: nodelvmstorage
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: NodeLVMStorage
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - lvm
  additionalPrinterColumns:
    - name: NodeName
      type: string
      description: node name
      JSONPath: .spec.nodeName
    - name: LvName
      type: string
      description: volume group name 
      JSONPath: .spec.lvName
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp