/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	controlv1 "k8s-crd-lvmnodestorage/pkg/apis/control/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeLvmVolumeGroups implements NodeLvmVolumeGroupInterface
type FakeNodeLvmVolumeGroups struct {
	Fake *FakeLvmV1
}

var nodelvmvolumegroupsResource = schema.GroupVersionResource{Group: "lvm.node.storage", Version: "v1", Resource: "nodelvmvolumegroups"}

var nodelvmvolumegroupsKind = schema.GroupVersionKind{Group: "lvm.node.storage", Version: "v1", Kind: "NodeLvmVolumeGroup"}

// Get takes name of the nodeLvmVolumeGroup, and returns the corresponding nodeLvmVolumeGroup object, and an error if there is any.
func (c *FakeNodeLvmVolumeGroups) Get(name string, options v1.GetOptions) (result *controlv1.NodeLvmVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nodelvmvolumegroupsResource, name), &controlv1.NodeLvmVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmVolumeGroup), err
}

// List takes label and field selectors, and returns the list of NodeLvmVolumeGroups that match those selectors.
func (c *FakeNodeLvmVolumeGroups) List(opts v1.ListOptions) (result *controlv1.NodeLvmVolumeGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nodelvmvolumegroupsResource, nodelvmvolumegroupsKind, opts), &controlv1.NodeLvmVolumeGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &controlv1.NodeLvmVolumeGroupList{ListMeta: obj.(*controlv1.NodeLvmVolumeGroupList).ListMeta}
	for _, item := range obj.(*controlv1.NodeLvmVolumeGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeLvmVolumeGroups.
func (c *FakeNodeLvmVolumeGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nodelvmvolumegroupsResource, opts))
}

// Create takes the representation of a nodeLvmVolumeGroup and creates it.  Returns the server's representation of the nodeLvmVolumeGroup, and an error, if there is any.
func (c *FakeNodeLvmVolumeGroups) Create(nodeLvmVolumeGroup *controlv1.NodeLvmVolumeGroup) (result *controlv1.NodeLvmVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nodelvmvolumegroupsResource, nodeLvmVolumeGroup), &controlv1.NodeLvmVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmVolumeGroup), err
}

// Update takes the representation of a nodeLvmVolumeGroup and updates it. Returns the server's representation of the nodeLvmVolumeGroup, and an error, if there is any.
func (c *FakeNodeLvmVolumeGroups) Update(nodeLvmVolumeGroup *controlv1.NodeLvmVolumeGroup) (result *controlv1.NodeLvmVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nodelvmvolumegroupsResource, nodeLvmVolumeGroup), &controlv1.NodeLvmVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmVolumeGroup), err
}

// Delete takes name of the nodeLvmVolumeGroup and deletes it. Returns an error if one occurs.
func (c *FakeNodeLvmVolumeGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(nodelvmvolumegroupsResource, name), &controlv1.NodeLvmVolumeGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeLvmVolumeGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nodelvmvolumegroupsResource, listOptions)

	_, err := c.Fake.Invokes(action, &controlv1.NodeLvmVolumeGroupList{})
	return err
}

// Patch applies the patch and returns the patched nodeLvmVolumeGroup.
func (c *FakeNodeLvmVolumeGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *controlv1.NodeLvmVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nodelvmvolumegroupsResource, name, pt, data, subresources...), &controlv1.NodeLvmVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmVolumeGroup), err
}
