/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	controlv1 "k8s-crd-lvmnodestorage/pkg/apis/control/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeLvmPhysicalVolumes implements NodeLvmPhysicalVolumeInterface
type FakeNodeLvmPhysicalVolumes struct {
	Fake *FakeLvmV1
}

var nodelvmphysicalvolumesResource = schema.GroupVersionResource{Group: "lvm.node.storage", Version: "v1", Resource: "nodelvmphysicalvolumes"}

var nodelvmphysicalvolumesKind = schema.GroupVersionKind{Group: "lvm.node.storage", Version: "v1", Kind: "NodeLvmPhysicalVolume"}

// Get takes name of the nodeLvmPhysicalVolume, and returns the corresponding nodeLvmPhysicalVolume object, and an error if there is any.
func (c *FakeNodeLvmPhysicalVolumes) Get(name string, options v1.GetOptions) (result *controlv1.NodeLvmPhysicalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nodelvmphysicalvolumesResource, name), &controlv1.NodeLvmPhysicalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmPhysicalVolume), err
}

// List takes label and field selectors, and returns the list of NodeLvmPhysicalVolumes that match those selectors.
func (c *FakeNodeLvmPhysicalVolumes) List(opts v1.ListOptions) (result *controlv1.NodeLvmPhysicalVolumeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nodelvmphysicalvolumesResource, nodelvmphysicalvolumesKind, opts), &controlv1.NodeLvmPhysicalVolumeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &controlv1.NodeLvmPhysicalVolumeList{ListMeta: obj.(*controlv1.NodeLvmPhysicalVolumeList).ListMeta}
	for _, item := range obj.(*controlv1.NodeLvmPhysicalVolumeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeLvmPhysicalVolumes.
func (c *FakeNodeLvmPhysicalVolumes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nodelvmphysicalvolumesResource, opts))
}

// Create takes the representation of a nodeLvmPhysicalVolume and creates it.  Returns the server's representation of the nodeLvmPhysicalVolume, and an error, if there is any.
func (c *FakeNodeLvmPhysicalVolumes) Create(nodeLvmPhysicalVolume *controlv1.NodeLvmPhysicalVolume) (result *controlv1.NodeLvmPhysicalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nodelvmphysicalvolumesResource, nodeLvmPhysicalVolume), &controlv1.NodeLvmPhysicalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmPhysicalVolume), err
}

// Update takes the representation of a nodeLvmPhysicalVolume and updates it. Returns the server's representation of the nodeLvmPhysicalVolume, and an error, if there is any.
func (c *FakeNodeLvmPhysicalVolumes) Update(nodeLvmPhysicalVolume *controlv1.NodeLvmPhysicalVolume) (result *controlv1.NodeLvmPhysicalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nodelvmphysicalvolumesResource, nodeLvmPhysicalVolume), &controlv1.NodeLvmPhysicalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmPhysicalVolume), err
}

// Delete takes name of the nodeLvmPhysicalVolume and deletes it. Returns an error if one occurs.
func (c *FakeNodeLvmPhysicalVolumes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(nodelvmphysicalvolumesResource, name), &controlv1.NodeLvmPhysicalVolume{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeLvmPhysicalVolumes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nodelvmphysicalvolumesResource, listOptions)

	_, err := c.Fake.Invokes(action, &controlv1.NodeLvmPhysicalVolumeList{})
	return err
}

// Patch applies the patch and returns the patched nodeLvmPhysicalVolume.
func (c *FakeNodeLvmPhysicalVolumes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *controlv1.NodeLvmPhysicalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nodelvmphysicalvolumesResource, name, pt, data, subresources...), &controlv1.NodeLvmPhysicalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*controlv1.NodeLvmPhysicalVolume), err
}
