/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s-crd-lvmnodestorage/pkg/apis/control/v1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NodeLVMStorageLister helps list NodeLVMStorages.
type NodeLVMStorageLister interface {
	// List lists all NodeLVMStorages in the indexer.
	List(selector labels.Selector) (ret []*v1.NodeLVMStorage, err error)
	// Get retrieves the NodeLVMStorage from the index for a given name.
	Get(name string) (*v1.NodeLVMStorage, error)
	NodeLVMStorageListerExpansion
}

// nodeLVMStorageLister implements the NodeLVMStorageLister interface.
type nodeLVMStorageLister struct {
	indexer cache.Indexer
}

// NewNodeLVMStorageLister returns a new NodeLVMStorageLister.
func NewNodeLVMStorageLister(indexer cache.Indexer) NodeLVMStorageLister {
	return &nodeLVMStorageLister{indexer: indexer}
}

// List lists all NodeLVMStorages in the indexer.
func (s *nodeLVMStorageLister) List(selector labels.Selector) (ret []*v1.NodeLVMStorage, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.NodeLVMStorage))
	})
	return ret, err
}

// Get retrieves the NodeLVMStorage from the index for a given name.
func (s *nodeLVMStorageLister) Get(name string) (*v1.NodeLVMStorage, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("nodelvmstorage"), name)
	}
	return obj.(*v1.NodeLVMStorage), nil
}
