/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s-crd-lvmnodestorage/pkg/apis/control/v1"
	scheme "k8s-crd-lvmnodestorage/pkg/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeLvmPhysicalVolumesGetter has a method to return a NodeLvmPhysicalVolumeInterface.
// A group's client should implement this interface.
type NodeLvmPhysicalVolumesGetter interface {
	NodeLvmPhysicalVolumes() NodeLvmPhysicalVolumeInterface
}

// NodeLvmPhysicalVolumeInterface has methods to work with NodeLvmPhysicalVolume resources.
type NodeLvmPhysicalVolumeInterface interface {
	Create(*v1.NodeLvmPhysicalVolume) (*v1.NodeLvmPhysicalVolume, error)
	Update(*v1.NodeLvmPhysicalVolume) (*v1.NodeLvmPhysicalVolume, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodeLvmPhysicalVolume, error)
	List(opts metav1.ListOptions) (*v1.NodeLvmPhysicalVolumeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeLvmPhysicalVolume, err error)
	NodeLvmPhysicalVolumeExpansion
}

// nodeLvmPhysicalVolumes implements NodeLvmPhysicalVolumeInterface
type nodeLvmPhysicalVolumes struct {
	client rest.Interface
}

// newNodeLvmPhysicalVolumes returns a NodeLvmPhysicalVolumes
func newNodeLvmPhysicalVolumes(c *LvmV1Client) *nodeLvmPhysicalVolumes {
	return &nodeLvmPhysicalVolumes{
		client: c.RESTClient(),
	}
}

// Get takes name of the nodeLvmPhysicalVolume, and returns the corresponding nodeLvmPhysicalVolume object, and an error if there is any.
func (c *nodeLvmPhysicalVolumes) Get(name string, options metav1.GetOptions) (result *v1.NodeLvmPhysicalVolume, err error) {
	result = &v1.NodeLvmPhysicalVolume{}
	err = c.client.Get().
		Resource("nodelvmphysicalvolumes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeLvmPhysicalVolumes that match those selectors.
func (c *nodeLvmPhysicalVolumes) List(opts metav1.ListOptions) (result *v1.NodeLvmPhysicalVolumeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodeLvmPhysicalVolumeList{}
	err = c.client.Get().
		Resource("nodelvmphysicalvolumes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeLvmPhysicalVolumes.
func (c *nodeLvmPhysicalVolumes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("nodelvmphysicalvolumes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodeLvmPhysicalVolume and creates it.  Returns the server's representation of the nodeLvmPhysicalVolume, and an error, if there is any.
func (c *nodeLvmPhysicalVolumes) Create(nodeLvmPhysicalVolume *v1.NodeLvmPhysicalVolume) (result *v1.NodeLvmPhysicalVolume, err error) {
	result = &v1.NodeLvmPhysicalVolume{}
	err = c.client.Post().
		Resource("nodelvmphysicalvolumes").
		Body(nodeLvmPhysicalVolume).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodeLvmPhysicalVolume and updates it. Returns the server's representation of the nodeLvmPhysicalVolume, and an error, if there is any.
func (c *nodeLvmPhysicalVolumes) Update(nodeLvmPhysicalVolume *v1.NodeLvmPhysicalVolume) (result *v1.NodeLvmPhysicalVolume, err error) {
	result = &v1.NodeLvmPhysicalVolume{}
	err = c.client.Put().
		Resource("nodelvmphysicalvolumes").
		Name(nodeLvmPhysicalVolume.Name).
		Body(nodeLvmPhysicalVolume).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodeLvmPhysicalVolume and deletes it. Returns an error if one occurs.
func (c *nodeLvmPhysicalVolumes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("nodelvmphysicalvolumes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeLvmPhysicalVolumes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("nodelvmphysicalvolumes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodeLvmPhysicalVolume.
func (c *nodeLvmPhysicalVolumes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeLvmPhysicalVolume, err error) {
	result = &v1.NodeLvmPhysicalVolume{}
	err = c.client.Patch(pt).
		Resource("nodelvmphysicalvolumes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
