/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s-crd-lvmnodestorage/pkg/apis/control/v1"
	scheme "k8s-crd-lvmnodestorage/pkg/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeLvmVolumeGroupsGetter has a method to return a NodeLvmVolumeGroupInterface.
// A group's client should implement this interface.
type NodeLvmVolumeGroupsGetter interface {
	NodeLvmVolumeGroups() NodeLvmVolumeGroupInterface
}

// NodeLvmVolumeGroupInterface has methods to work with NodeLvmVolumeGroup resources.
type NodeLvmVolumeGroupInterface interface {
	Create(*v1.NodeLvmVolumeGroup) (*v1.NodeLvmVolumeGroup, error)
	Update(*v1.NodeLvmVolumeGroup) (*v1.NodeLvmVolumeGroup, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodeLvmVolumeGroup, error)
	List(opts metav1.ListOptions) (*v1.NodeLvmVolumeGroupList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeLvmVolumeGroup, err error)
	NodeLvmVolumeGroupExpansion
}

// nodeLvmVolumeGroups implements NodeLvmVolumeGroupInterface
type nodeLvmVolumeGroups struct {
	client rest.Interface
}

// newNodeLvmVolumeGroups returns a NodeLvmVolumeGroups
func newNodeLvmVolumeGroups(c *LvmV1Client) *nodeLvmVolumeGroups {
	return &nodeLvmVolumeGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the nodeLvmVolumeGroup, and returns the corresponding nodeLvmVolumeGroup object, and an error if there is any.
func (c *nodeLvmVolumeGroups) Get(name string, options metav1.GetOptions) (result *v1.NodeLvmVolumeGroup, err error) {
	result = &v1.NodeLvmVolumeGroup{}
	err = c.client.Get().
		Resource("nodelvmvolumegroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeLvmVolumeGroups that match those selectors.
func (c *nodeLvmVolumeGroups) List(opts metav1.ListOptions) (result *v1.NodeLvmVolumeGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodeLvmVolumeGroupList{}
	err = c.client.Get().
		Resource("nodelvmvolumegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeLvmVolumeGroups.
func (c *nodeLvmVolumeGroups) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("nodelvmvolumegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodeLvmVolumeGroup and creates it.  Returns the server's representation of the nodeLvmVolumeGroup, and an error, if there is any.
func (c *nodeLvmVolumeGroups) Create(nodeLvmVolumeGroup *v1.NodeLvmVolumeGroup) (result *v1.NodeLvmVolumeGroup, err error) {
	result = &v1.NodeLvmVolumeGroup{}
	err = c.client.Post().
		Resource("nodelvmvolumegroups").
		Body(nodeLvmVolumeGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodeLvmVolumeGroup and updates it. Returns the server's representation of the nodeLvmVolumeGroup, and an error, if there is any.
func (c *nodeLvmVolumeGroups) Update(nodeLvmVolumeGroup *v1.NodeLvmVolumeGroup) (result *v1.NodeLvmVolumeGroup, err error) {
	result = &v1.NodeLvmVolumeGroup{}
	err = c.client.Put().
		Resource("nodelvmvolumegroups").
		Name(nodeLvmVolumeGroup.Name).
		Body(nodeLvmVolumeGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodeLvmVolumeGroup and deletes it. Returns an error if one occurs.
func (c *nodeLvmVolumeGroups) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("nodelvmvolumegroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeLvmVolumeGroups) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("nodelvmvolumegroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodeLvmVolumeGroup.
func (c *nodeLvmVolumeGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeLvmVolumeGroup, err error) {
	result = &v1.NodeLvmVolumeGroup{}
	err = c.client.Patch(pt).
		Resource("nodelvmvolumegroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
