/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	controlv1 "k8s-crd-lvmnodestorage/pkg/apis/control/v1"
	versioned "k8s-crd-lvmnodestorage/pkg/client/clientset/versioned"
	internalinterfaces "k8s-crd-lvmnodestorage/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s-crd-lvmnodestorage/pkg/client/listers/control/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NodeLvmPhysicalVolumeInformer provides access to a shared informer and lister for
// NodeLvmPhysicalVolumes.
type NodeLvmPhysicalVolumeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NodeLvmPhysicalVolumeLister
}

type nodeLvmPhysicalVolumeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNodeLvmPhysicalVolumeInformer constructs a new informer for NodeLvmPhysicalVolume type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeLvmPhysicalVolumeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodeLvmPhysicalVolumeInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNodeLvmPhysicalVolumeInformer constructs a new informer for NodeLvmPhysicalVolume type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodeLvmPhysicalVolumeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LvmV1().NodeLvmPhysicalVolumes().List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LvmV1().NodeLvmPhysicalVolumes().Watch(options)
			},
		},
		&controlv1.NodeLvmPhysicalVolume{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodeLvmPhysicalVolumeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodeLvmPhysicalVolumeInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodeLvmPhysicalVolumeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&controlv1.NodeLvmPhysicalVolume{}, f.defaultInformer)
}

func (f *nodeLvmPhysicalVolumeInformer) Lister() v1.NodeLvmPhysicalVolumeLister {
	return v1.NewNodeLvmPhysicalVolumeLister(f.Informer().GetIndexer())
}
